export default {
    a: "inrulsvtcpmbgdfq",
    b: "lorieaustjbd",
    c: "eohairutlcsydq",
    d: "eeeeaiuorsdmglpcnjqt",
    e: "sntrlmcdupeavqfigbjzoxhywk",
    f: "aoiefrulstdcqm",
    g: "eranuioltmsdy",
    h: "eaoiuytrbmnlc",
    i: "teslnromdvcagqfpbxjiu",
    j: "eeoau",
    k: "eisalrodphykjfcwqmgut",
    l: "eeeaaliuosqndhtpyfcm",
    m: "eeaoimpbud",
    n: "tesdcaoingp",
    o: "nnuuirmlts",
    p: "aeorlipusthd",
    q: "u",
    r: "eeeaiostdlcr",
    s: "eeasidotlpcuqm",
    t: "eearidolstpucq",
    u: "resintxlvacpdm",
    v: "eaoiru",
    w: "aeinoshylrjktcdqpm",
    x: "pedacitqmslfhvobrnjguyx",
    y: "aesrpolmctdbvfnigq",
    z: "evldapmocsqibutrnfjgz",
};