export default [
    "Aarakocra",
    "Aasimar",
    "Air Genasi",
    "Bugbear",
    "Centaur",
    "Changeling",
    "Deep Gnome",
    "Duergar",
    "Earth Genasi",
    "Eladrin",
    "Fairy",
    "Firbolg",
    "Fire Genasi",
    "Githyanki",
    "Githzerai",
    "Goblin",
    "Goliath",
    "Harengon",
    "Hobgoblin",
    "Kenku",
    "Kobold",
    "Lizardfolk",
    "Minotaur",
    "Orc",
    "Satyr",
    "Sea Elf",
    "Shadar-kai",
    "Shifter",
    "Tabaxi",
    "Tortle",
    "Triton",
    "Water Genasi",
    "Yuan-ti",
];